-- supabase/seed.sql

-- Insert Websites
INSERT INTO "public"."websites" ("id", "title", "description", "category", "tags", "image", "url") VALUES
('mj-1', 'Midjourney', 'The premier AI art generation tool. Create stunning visuals from simple text prompts in a Discord-native environment.', 'Image Gen', ARRAY['Creative', 'Discord'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvIDHd_nZN0P-8DESqEmDLJZWa6CoyfRA1Pus8hdpPp57o0InZJID8OdQT2UwG6aA6_t4Ec9JxJXyseCXeGKAE9u0jhORx67zUna1f0OgxV_HqiIsEN6hXdgTGyER8oA4M1TBIl7CXCHd3Ws54JDKWvdoNZ9SfJlBTCsaOwyutshGFpq1K_ZJcC7MGrf2a4HCjbGZzvwYteG3I5_Gs5a41JtMysbZ6ESYstJ0ZZ315TPFkkT4p0frSBnyyZQKIJKIFGbQjJdI--JA', 'https://www.midjourney.com'),
('claude-1', 'Claude 3.5 Sonnet', 'Anthropic''s latest model. Excels at complex reasoning, coding, and highly nuanced creative writing with a human-like tone.', 'LLM', ARRAY['Coding', 'Free Tier'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtU1hIRH83mx84a4Zt-yHqFE9vs4StFbYZHaAaNm1ojw9JqrA8rjLplzrCFB3Ufejsc2zH5YIKRgfZPB0MfxV99zwgpzhZNkCN5pWEjjrVcZKIvUqunxp7dZTjKiWHsA1gGG1PQ6FupMhpl3IhrPdvyo1D4Uecpn7DjB96se0JUaCMH2tjhr6oUtwit7N9P97AhzsnYNfM7Dc-0buFc3OpzW55Hy3vuduOZPp9tzuRO-9-MTxEGK89Su7QErRkrRTSIzZPu0yzBY4', 'https://claude.ai'),
('perplexity-1', 'Perplexity AI', 'The future of search. Get direct answers with cited sources across the web in a real-time conversational format.', 'Search', ARRAY['Research', 'Productivity'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuC9LVa1F0-YnIz_prI5_LGm5jc09gcEf6R7HCVZhJfojZxEhQdx12ii8pbcfe3fvLW_zUffYNpUniTLPmWYBGS2Ux5FDOh-qLSjMpI_dmz03_KRWVb7_gmGOnX5oMi_lbEypmrZmWnGe1ftunDFAoWiwFWBzd_yrkbON6MVWDtbxTUDj4qjitN3SgdoiSuKi_nQxcHd3x_CgCymw8L9Yn2rSyoihGFxuGf7U25fIevX85Hw4wwd8_pBboXlKA6ucVmVlUZJnrDqjpg', 'https://www.perplexity.ai');

-- Insert Prompts
INSERT INTO "public"."prompts" ("id", "title", "description", "category", "tags", "image", "rating", "positive", "negative", "model", "sampler", "steps", "cfg", "seed", "size") VALUES
('p1', '赛博流体艺术 第一卷', 'Abstract 3D fluid art with neon green glow', '插画', ARRAY['科技'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0nQSfvq-FglzJin4ijkRwNVC1MJhY2UvVGO9OlByp2DsLxuhAJtfvOA-__BhOjEXdcxQ9OlX3-d_hVUKMLv0rBbPa3S96bBESyHoWOjl5BtCiqb9MBpJ_HMxN6_wonczf13LQ2ppDtxpNNAe41KoLxthb0gKL26nes2l68WrxR1RzHv1yiD-oxQr-ELZYkBnvcVuTGNxCdtDWRYAqX10ln4EJ28zTTsB0dV5fHnfC6b78-B0YqVRSe6QmsRK7ixyxLksyjFkAv3I', 4.0, 'Masterpiece, best quality, ultra-detailed, cinematic lighting, complex background, 8k resolution, ethereal digital alchemy experiment, flowing vibrant energy ribbons, obsidian laboratory environment, neon green highlights, volumetric fog, hyper-realistic textures.', 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry.', 'Stable Diffusion XL', 'DPM++ 2M Karras', 35, 7.5, '2983741029', '1024 x 1024'),
('p2', '空灵界面渐变', 'Minimalist geometric gradient background', 'UI 设计', ARRAY['极简'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoUE71xnMlogjwCaDndYWBBemETQRnmQF5F9m4uECqzY-NmpM6uFbHXdYVL1U0pmhQCdQOGkdmDGt2mcd9WGNogYqB6KdwO6aqa9BaJMFhQtjCeMrmuNm-ngHAq_vUCPIqrGI9MnuAYlB5ZtiCXkYmh6KKk22DnE_R2O_YW2YVnqBH6aQfE9TTwNIZ8fAtUtwesdKprE4ZCjm9XQ0REkuusYUlL-PuJ5x5vPNCBnaxIQFyQltSa4VQe5dnTEjiE-O-5MIgbJLcYRo', 5.0, 'Minimalist UI gradient, soft ethereal colors, high-end tech aesthetic, clean lines, 4k, vector style.', 'cluttered, noisy, dark, low contrast.', 'DALL-E 3', 'Default', 20, 6.0, '123456789', '1024 x 1024');

-- Insert Cases
INSERT INTO "public"."cases" ("id", "title", "description", "category", "tags", "image", "status") VALUES
('c1', '赛博有机界面协议：视觉熵案例研究', '探索如何利用 Stable Diffusion 与 ControlNet 在 48 小时内完成整套品牌视觉输出。', 'Synthetic Ether', ARRAY['ETH-0922'], 'https://lh3.googleusercontent.com/aida-public/AB6AXuDbYB9KTazCc3AIYw87jPqqUlEme4IEiov75aaX2qI5jakwGi8PciQb4hEUHPahoe5o2wJ44YgqoEDwXynWmEOoPMPkfwzSr1P3iI8a6gb2S94m8PsxgE2Oj1pgiUZQDcZQPWhBOF3ojsDffBd27EnEmxMGg5UeqT6ciCcbFmNIU4YdkcPHMnUigVaf33kyGx3SihfJCkDXfoV0KDphn3SnJspZnZ3GN3hwNKmBybVrKw17fTq0dNEaYIUC608EoL1F8Jwh0gdK_lk', '已验证结果');

-- Insert Case Logs
INSERT INTO "public"."cases_logs" ("id", "case_id", "title", "time", "description", "images") VALUES
('l1', 'c1', '初步合成', '14:22:05 UTC', '专注于玻璃和有机物之间的材料对比。结果太暗，发光度不足。', ARRAY['https://lh3.googleusercontent.com/aida-public/AB6AXuDkaYPZJGyoQw8ThKXD59c6puc4UjThPAIfc8O9DmP8phje58TA-XyLm9tjtLvoZlB2QJEh2biVxGSR-D-D3Lqj90gHCOLSReZzJyz5XOjxaIGvoEl4d8l1dy74m4lVszh05-n-9XE6rR0ojgiBh3Nj9eHjpr-8X7jb73BBZatVoAegPEYrfN9Igc3_KY8R1y2biY_HW1dvUbuwHfhhWst7TNRh60200_ixmCcdlNEWj0AxHiherPuxLTw2UFiyej-De-K5SVkyd6g', 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3VXcHIBMGH_a2U4viDTNwcvVVKRsjpt7qnQn1Ram-lOuoU6WcMBcIp7YBZOtfckIouS6ol1v2zKYJ78URVVWBJmre-bMX5l48Vt0zL7hxlRmHwC9Ro3mWmrl7-pPAMSCxQdlsvgO5TWzAHxbeqxI2vZ6FsrSHlxEHafGEq8rBK3Y6DOtOWhMefZbiUnWCUbr8xX6kJ0oTQtDGH6zE6ltyf1V0depEN1mCHU5U_MDCx6ANgZ6C1hUGTd7qIIzYp0ndzUstN8ED4jo']),
('l2', 'c1', '光影调整', '15:45:12 UTC', '添加了''体积绿光''和''octane render''以提高清晰度。在黑曜石表面上有更好的光折射。', ARRAY['https://lh3.googleusercontent.com/aida-public/AB6AXuDhe1THdOO4_PZ9vlroqXw4H7VrAzR5twIoGn0EdcxApVE8d4iSr3GsHVNbNEyO8-jeHvqiSHgQpH4HEtBi8DQeGeXc4icZnH2I_ymg4tQFHZyOLE81jk78EwBvRXLioAU16vUEJKlsBYYAuHJaAy81s-ZOEE0j3p7YngSLONJO255Ia2DrE3DiiRvW7Q_mULA2eUVUaldmXik5QQVxGXCw6PRETAWmPx4LUzr2pkK3nBUbzlrFMnGgmdYRnMS1TxbTXSKyFLr3el4', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoWbDHFdkRVEJ29FZ-8doOZ4YmVnqLw68VhUrKZdkuLdtCwjiJiEogCEWxkB9eIOT3IY-g0-IRtLTDmZhrhe0kBaK1sHZkdhD1EbCmUC7t7TCD6Hl5Zwa9K4uW6kNAPhMi5jJ-nbJ6OQn9ow6Ui9bNiXhDy_Bd7EuhAXFYuhxI74A2gl-C8Skx-j99B74LcwEgFBKcezZoxw30nIfh8R8zg9abRPrySDnf3fnsPonIvZCjXL1W40TIdTfzetLje1ZANClOMW57nHo']);
